- name: Copy catalogue.service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: System daemon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes